# Dockerfile (frontend)
FROM node:22.19.0-bookworm
WORKDIR /goldfren_frontend

# 1. copy lock‑files a package
COPY package.json package-lock.json ./

# 2. install dependencies
RUN npm i -g npm@11.6.0 \
 && rm -rf node_modules package-lock.json \
 && npm install --include=optional     

# 3. copy the rest and build
COPY . .
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]