# Use alpine Node.js image
FROM node:25.1.0-alpine
WORKDIR /goldfren_frontend

# Declare build argument and environment variables
ARG VITE_API_URL
ARG VITE_APP_VERSION
ARG VITE_GA_ID

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_GA_ID=$VITE_GA_ID

# 1. Copy lockfiles & package.json
COPY Frontend/package.json Frontend/package-lock.json ./

# 2. Install dependencies
RUN npm cache clean --force && \
    npm install --include=optional && \
    npm install --save-dev terser 

# 3. Copy the rest of the code
COPY Frontend/ .

# 4. Run react vite build
RUN npm run build