# Use alpine Node.js image
FROM node:24.10.0-alpine
WORKDIR /goldfren_frontend

# 1. Copy lockfiles & package.json
COPY package.json package-lock.json ./

# 2. Install dependencies
RUN npm install -g npm@11.6.1 && \
    npm cache clean --force && \
    npm install --include=optional

# 3. Copy the rest of the code
COPY . .

# 4. Run react vite build
RUN npm run build