# Build React/Vite app
FROM node:26.4.0-alpine AS frontend_build
WORKDIR /goldfren_frontend

# Declare build argument and environment variables
ARG VITE_API_URL
ARG VITE_APP_VERSION
ARG VITE_GA_ID

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_GA_ID=$VITE_GA_ID

# 1. Copy lockfiles & package.json
COPY Frontend/package.json Frontend/package-lock.json ./

# 2. Install dependencies
RUN npm ci --include=optional

# 3. Copy the rest of the code
COPY Frontend/ .

# 4. Run react vite build command 
RUN npm run build

# Serve build with Nginx
FROM nginx:1.31.2-alpine

COPY Docker/nginx/default.prod.conf /etc/nginx/conf.d/default.conf
COPY Docker/nginx/security-headers.conf /etc/nginx/conf.d/security-headers.conf
COPY nginx/ssl-params.conf /etc/nginx/snippets/ssl-params.conf
COPY --from=frontend_build /goldfren_frontend/dist /usr/share/nginx/html
