# Use alpine Node.js image
FROM node:24.11.0-alpine
WORKDIR /goldfren_frontend

# 1. Copy lockfiles & package.json
COPY Frontend/package.json Frontend/package-lock.json ./

# 2. Install dependencies
RUN npm cache clean --force && \
    npm install --include=optional

# 3. Copy the rest of the code
COPY Frontend/ .

# 4. Expose port
EXPOSE 3000

# 5. Run dev server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]