export const dialogColumnsConfig = {
  user: {
    primaryKey: "id",
    editEndpoint: (id) => `/api/goldfren/internal/users/${id}`,
    fields: [
      {
        key: "id",
        label: "ID",
        type: "text",
        editable: false,
        show: false,
        dataType: "string",
      },
      {
        key: "username",
        label: "Uživatelské jméno",
        type: "input",
        editable: false,
        show: true,
        dataType: "string",
      },
      {
        key: "first_name",
        label: "Křestní jméno",
        type: "input",
        editable: true,
        show: true,
        dataType: "string",
      },
      {
        key: "last_name",
        label: "Přijmení",
        type: "input",
        editable: true,
        show: true,
        dataType: "string",
      },
      {
        key: "email",
        label: "E-mail",
        type: "input",
        editable: true,
        show: true,
        dataType: "string",
      },
      {
        key: "is_staff",
        label: "Administrátorská práva",
        type: "button",
        buttonValue: { true: "Ano", false: "Ne" },
        editable: false,
        show: true,
        dataType: "boolean",
      },
      {
        key: "is_valid",
        label: "Status účtu",
        type: "button",
        buttonValue: { true: "Aktivní", false: "Deaktivován" },
        editable: true,
        show: true,
        dataType: "boolean",
      },
      {
        key: "date_joined",
        label: "Datum registrace uživatele",
        type: "text",
        editable: false,
        show: true,
        dataType: "date",
      },
      {
        key: "last_login",
        label: "Poslední přihlášení",
        type: "text",
        editable: false,
        show: true,
        dataType: "date",
      },
    ],
  },

};
