server {
    listen 80;
    server_name localhost;

    # Maximal image size for upload
    client_max_body_size 10M;

    # Encoding for website
    charset utf-8;

    # Serve icons
    location /icons/ {
        alias /shared/public/icons/;
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # Serve logo
    location /logo/ {
        alias /shared/public/logo/;
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # Server DJANGO media files
    location /GoldFren_Media/ {
        alias /GoldFren_Media/;
        autoindex off;
        add_header Cache-Control "public, max-age=31536000, immutable";
        access_log off;
    }

    # Admin access for DJANGO
    location ^~ /django-admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy for public API
    location /api/goldfren/public/ {
        proxy_pass http://backend:8000/api/goldfren/public/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    #  Server static files for admin access
    location /static/ {
        alias /usr/share/nginx/html/static/;
        try_files $uri $uri/ =404;
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # Proxy private API – only internal net allowed
    location /api/ {
        allow 172.20.0.0/16;
        allow 192.168.0.0/16;
        allow 127.0.0.1;
        allow all;

        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Serve React APP
    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Force UTF-8 for HTML/JS content
        add_header Content-Type "text/html; charset=utf-8";
    }
}
