server {
    listen 80;
    server_name localhost;

    client_max_body_size 10M;

    location /GoldFren_Media/ {
        alias /GoldFren_Media/;
        autoindex on;
    }

    location /admin {
        proxy_pass http://backend:8000/admin;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/goldfren/public/ {
        proxy_pass http://backend:8000/api/goldfren/public/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        alias /usr/share/nginx/html/static/;
        try_files $uri $uri/ =404;
    }

    location /api/ {
        allow 172.20.0.0/16;
        allow 192.168.0.0/16;
        allow 127.0.0.1;
        deny all;

        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
