server {
    listen 80;
    server_name localhost;
    client_max_body_size 10M;

    # Server DJANGO media files
    location /GoldFren_Media/ {
        alias /GoldFren_Media/;
        autoindex on;
    }

    # Admin access for DJANGO
    location /admin {
        proxy_pass http://backend:8000/admin;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy for public API
    location /api/goldfren/public/ {
        proxy_pass http://backend:8000/api/goldfren/public/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    #  Server static files for admin access
    location /static/ {
        alias /usr/share/nginx/html/static/;
        try_files $uri $uri/ =404;
    }

    # Proxy private API – only internal net allowed
    location /api/ {
        allow 172.20.0.0/16;
        allow 192.168.0.0/16;
        allow 127.0.0.1;
        deny all;

        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Serve React APP
    location / {
        proxy_pass         http://frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header   Host            $host;
        proxy_set_header   X-Real-IP       $remote_addr;

        # support HMR if you ever switch to dev mode:
        proxy_set_header   Upgrade         $http_upgrade;
        proxy_set_header   Connection      "upgrade";
    }
}
