import i18next from "i18next";
const serverUrl = import.meta.env.VITE_API_URL;

// Categories for filtering
export const categories = [
  {
    key: "motorbike",
    label: i18next.t("category.motorbike"),
    icon: "motorbike",
    type: "vehicle",
    id: 1,
    api: `${serverUrl}/api/goldfren/internal/vozidla/sortiment?vozidlo_kod=`,
  },
  {
    key: "car",
    label: i18next.t("category.car"),
    icon: "car",
    type: "vehicle",
    id: 2,
    api: `${serverUrl}/api/goldfren/internal/vozidla/sortiment?vozidlo_kod=`,
  },
  {
    key: "kart",
    label: i18next.t("category.kart"),
    icon: "kart",
    type: "vehicle",
    id: 6,
    api: `${serverUrl}/api/goldfren/internal/vozidla/sortiment?vozidlo_kod=`,
  },
  {
    key: "bike",
    label: i18next.t("category.bike"),
    icon: "bike",
    type: "vehicle",
    id: 3,
    api: `${serverUrl}/api/goldfren/internal/vozidla/sortiment?vozidlo_kod=`,
  },
  {
    key: "plane",
    label: i18next.t("category.plane"),
    icon: "plane",
    type: "vehicle",
    id: 4,
    api: `${serverUrl}/api/goldfren/internal/vozidla/sortiment?vozidlo_kod=`,
  },
  {
    key: "industry",
    label: i18next.t("category.industry"),
    icon: "industry",
    type: "vehicle",
    id: 5,
    api: `${serverUrl}/api/goldfren/internal/vozidla/sortiment?vozidlo_kod=`,
  },
  {
    key: "pad",
    label: i18next.t("category.pad"),
    icon: "pad",
    type: "sortiment",
    id: 1,
    api: `${serverUrl}/api/goldfren/internal/desticky/filter?limit=0`,
  },
  {
    key: "caliper",
    label: i18next.t("category.caliper"),
    icon: "caliper",
    type: "sortiment",
    id: 3,
    api: `${serverUrl}/api/goldfren/internal/brzdice/filter?limit=0`,
  },
  {
    key: "adapter",
    label: i18next.t("category.adapter"),
    icon: "adapter",
    type: "sortiment",
    id: 6,
    api: `${serverUrl}/api/goldfren/internal/adaptery/filter?limit=0`,
  },
  {
    key: "disc",
    label: i18next.t("category.disc"),
    icon: "disc",
    type: "sortiment",
    id: 2,
    api: `${serverUrl}/api/goldfren/internal/kotouce/filter?limit=0`,
  },
];
