// Specific configuration for filters based on category
export const filterConfigs = {
  motorbike: [
    {
      name: "vyrobce",
      label: "search.manufacturer_motorbike",
      placeholder: "search.manufacturer_motorbike_placeholder",
      type: "select",
      options: [],
      getDataAPI: "/api/goldfren/internal/vozidla/vyrobce",
      getDataAPI_params: ["kategorie_kod"]
    },
    {
      name: "objem",
      label: "search.motor_volume",
      placeholder: "search.motor_volume_placeholder",
      type: "select",
      options: [],
      dependsOn: "vyrobce",
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/filter",
      getDataAPI_params: ["kategorie_kod", "vyrobce" ]
    },
    {
      name: "model",
      label: "search.motorbike_model",
      placeholder: "search.motorbike_model_placeholder",
      type: "select",
      options: [],
      dependsOn: "objem",
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/filter",
      getDataAPI_params: ["kategorie_kod", "vyrobce", "objem" ]
    },
    {
      name: "year",
      label: "search.year_manufactured",
      placeholder: "search.year_manufactured_placeholder",
      type: "select",
      optional: true,
      dependsOn: "model",
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/filter",
      getDataAPI_params: ["kategorie_kod", "vyrobce", "objem", "model" ]
    },
  ],
  car: [
    {
      name: "vyrobce",
      label: "search.manufacturer_car",
      placeholder: "search.manufacturer_car_placeholder",
      type: "select",
      options: [],
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/vyrobce",
      getDataAPI_params: ["kategorie_kod"]
    },
    {
      name: "objem",
      label: "search.motor_volume",
      placeholder: "search.motor_volume_placeholder",
      type: "select",
      options: [],
      dependsOn: "vyrobce",
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/filter",
      getDataAPI_params: ["kategorie_kod", "vyrobce" ]
    },
    {
      name: "model",
      label: "search.car_model",
      placeholder: "search.car_model_placeholder",
      type: "select",
      options: [],
      dependsOn: "objem",
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/filter",
      getDataAPI_params: ["kategorie_kod", "vyrobce", "objem" ]
    },
    {
      name: "year",
      label: "search.year_manufactured",
      placeholder: "search.year_manufactured_placeholder",
      type: "select",
      optional: true,
      dependsOn: "model",
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/filter",
      getDataAPI_params: ["kategorie_kod", "vyrobce", "objem", "model" ]
    },
  ],
  kart: [
    {
      name: "vyrobce",
      label: "search.manufacturer_kart",
      placeholder: "search.manufacturer_kart_placeholder",
      type: "select",
      options: [],
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/vyrobce",
      getDataAPI_params: ["kategorie_kod"]
    },
    {
      name: "objem",
      label: "search.motor_volume",
      placeholder: "search.motor_volume_placeholder",
      type: "select",
      options: [],
      dependsOn: "vyrobce",
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/filter",
      getDataAPI_params: ["kategorie_kod", "vyrobce" ]
    },
    {
      name: "model",
      label: "search.kart_model",
      placeholder: "search.kart_model_placeholder",
      type: "select",
      options: [],
      dependsOn: "objem",
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/filter",
      getDataAPI_params: ["kategorie_kod", "vyrobce", "objem" ]
    },
    {
      name: "year",
      label: "search.year_manufactured",
      placeholder: "search.year_manufactured_placeholder",
      type: "select",
      optional: true,
      dependsOn: "model",
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/filter",
      getDataAPI_params: ["kategorie_kod", "vyrobce", "objem", "model" ]
    },
  ],
  bike: [
    {
      name: "vyrobce",
      label: "search.manufacturer_bike",
      placeholder: "search.manufacturer_bike_placeholder",
      type: "select",
      options: [],
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/vyrobce",
      getDataAPI_params: ["kategorie_kod"]
    },
    {
      name: "model",
      label: "search.bike_model",
      placeholder: "search.bike_model_placeholder",
      type: "select",
      options: [],
      dependsOn: "vyrobce",
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/filter",
      getDataAPI_params: ["kategorie_kod", "vyrobce" ]
    },
    {
      name: "year",
      label: "search.year_manufactured",
      placeholder: "search.year_manufactured_placeholder",
      type: "select",
      optional: true,
      dependsOn: "model",
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/filter",
      getDataAPI_params: ["kategorie_kod", "vyrobce", "model" ]
    },
  ],
  plane: [
    {
      name: "vyrobce",
      label: "search.manufacturer_plane",
      placeholder: "search.manufacturer_plane_placeholder",
      type: "select",
      options: [],
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/vyrobce",
      getDataAPI_params: ["kategorie_kod"]
    },
    {
      name: "objem",
      label: "search.motor_volume",
      placeholder: "search.motor_volume_placeholder",
      type: "select",
      options: [],
      dependsOnShow: true,
      dependsOn: "vyrobce",
      getDataAPI: "/api/goldfren/internal/vozidla/filter",
      getDataAPI_params: ["kategorie_kod", "vyrobce" ]
    },
    {
      name: "model",
      label: "search.plane_model",
      placeholder: "search.plane_model_placeholder",
      type: "select",
      options: [],
      dependsOnShow: true,
      dependsOn: "objem",
      getDataAPI: "/api/goldfren/internal/vozidla/filter",
      getDataAPI_params: ["kategorie_kod", "vyrobce", "objem" ]
    },
    {
      name: "year",
      label: "search.year_manufactured",
      placeholder: "search.year_manufactured_placeholder",
      type: "select",
      optional: true,
      dependsOnShow: true,
      dependsOn: "model",
      getDataAPI: "/api/goldfren/internal/vozidla/filter",
      getDataAPI_params: ["kategorie_kod", "vyrobce", "objem", "model" ]
    },
  ],
  industry: [
    {
      name: "vyrobce",
      label: "search.manufacturer_industry",
      placeholder: "search.manufacturer_industry_placeholder",
      type: "select",
      options: [],
      dependsOnShow: true,
      getDataAPI: "/api/goldfren/internal/vozidla/vyrobce",
      getDataAPI_params: ["kategorie_kod"]
    },
    {
      name: "model",
      label: "search.industry_model",
      placeholder: "search.industry_model_placeholder",
      type: "select",
      options: [],
      dependsOnShow: true,
      dependsOn: "vyrobce",
      getDataAPI: "/api/goldfren/internal/vozidla/filter",
      getDataAPI_params: ["kategorie_kod", "vyrobce" ]
    },
  ],
  pad: [
    {
      name: "konkurence",
      label: "search.pad.competitor",
      placeholder: "search.pad.competitor_placeholder",
      type: "text",
      optional: true,
    },
    {
      name: "material",
      label: "search.pad.material",
      placeholder: "search.pad.material_placeholder",
      type: "text",
      optional: true,
    },
    {
      name: "oem_cisla",
      label: "search.pad.oem_numbers",
      placeholder: "search.pad.oem_numbers_placeholder",
      type: "text",
      optional: true,
    },
  ],
  caliper: [
    {
      name: "pozice",
      label: "search.caliper.position",
      placeholder: "search.caliper.position_placeholder",
      type: "select",
      optional: true,
      options: ["FL caliper", "FR caliper", "RL caliper", "RR caliper"],
    },
    {
      name: "pocet_pistku",
      label: "search.caliper.piston_count",
      type: "range-slider",
      minValue: 0,
      maxValue: 20,
      step: 1,
      optional: true,
    },
    {
      name: "typ_uchyceni",
      label: "search.caliper.attachment_type",
      placeholder: "search.caliper.attachment_type_placeholder",
      type: "select",
      optional: true,
      options: ["Axis", "Radial"],
    },
  ],
  adapter: [
    {
      name: "pozice",
      label: "search.adapter.position",
      placeholder: "search.adapter.position_placeholder",
      type: "select",
      optional: true,
      options: ["FL adapter", "FR adapter", "RL adapter", "RR adapter"],
    },
    {
      name: "prumer",
      label: "search.adapter.diameter",
      type: "range-slider",
      minValue: 0,
      maxValue: 200,
      step: 1,
      optional: true,
    },
    {
      name: "uchyceni",
      label: "search.adapter.attachment",
      placeholder: "Please select brake adapter attachment",
      type: "select",
      options: ["Axis", "Radial"],
      optional: true,
    },
    {
      name: "roztec",
      label: "search.adapter.bolt_spacing",
      type: "range-slider",
      minValue: 0,
      maxValue: 200,
      step: 1,
      dependsOn: "uchyceni",
      dependsOnValue: "Radial",
    },
  ],
  disc: [
    {
      name: "vnejsi_prumer",
      label: "search.discs.outside_diameter",
      type: "range-slider",
      minValue: 0,
      maxValue: 200,
      step: 1,
      dependsOnShow: true,
    },
    {
      name: "roztecny_prumer",
      label: "search.discs.pitch_diameter",
      type: "range-slider",
      minValue: 0,
      maxValue: 200,
      step: 1,
      dependsOnShow: true,
    },
    {
      name: "vnitrni_prumer",
      label: "search.discs.inner_diameter",
      type: "range-slider",
      minValue: 0,
      maxValue: 200,
      step: 1,
      dependsOnShow: true,
    },
    {
      name: "tloustka",
      label: "search.discs.thickness",
      type: "range-slider",
      minValue: 0,
      maxValue: 200,
      step: 1,
      dependsOnShow: true,
    },
    {
      name: "typ",
      label: "search.discs.type",
      placeholder: "search.discs.type_placeholder",
      type: "select",
      options: ["OEM", "Oversize"],
      optional: true,
    },
  ],
};
